# Path to sources
sonar.sources=example,frozen,include,ricepp,sfx,src,tools
sonar.exclusions=**/test/**,include/dwarfs/internal/boost_move_only_function.hpp
#sonar.inclusions=

# Path to tests
sonar.tests=test,ricepp/test,frozen/thrift/lib/cpp2/frozen/test
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
