# syntax=docker/dockerfile:1

# SPDX-FileCopyrightText: Copyright (c) Marcus Holland-Moritz
# SPDX-License-Identifier: MIT

FROM archlinux:latest@sha256:b860afd5823683f7ea389ba5f00d812f4fe55f6f286dea329d2abeefa535e309
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm --needed \
        bash-completion \
        vim \
        devtools \
        less
RUN pacman -S --noconfirm --needed \
        gcc \
        clang \
        git \
        zstd \
        ccache \
        ninja \
        cmake \
        make \
        bison \
        mandoc \
        bubblewrap \
        flex \
        python-markdown-it-py \
        fuse \
        fuse3 \
        pkg-config \
        binutils \
        libarchive \
        benchmark \
        boost \
        boost-libs \
        brotli \
        openssl \
        fmt \
        range-v3 \
        nlohmann-json \
        jemalloc \
        lz4 \
        xz \
        xxhash \
        libunwind \
        libdwarf \
        flac \
        utf8cpp
RUN useradd -g users -u 1000 -m mhx
USER mhx
ENTRYPOINT /workspace/.docker/build-linux.sh
