# syntax=docker/dockerfile:1
FROM alpine:latest AS export
RUN apk add --no-cache rsync

RUN --mount=type=cache,id=ccache,target=/root/.ccache --mount=type=cache,id=pkgcache,target=/root/.pkgcache \
    rsync -a --delete /root/.ccache/ 192.168.1.60::docker-cache/ccache-$(uname -m)/ && \
    rsync -a /root/.pkgcache/ 192.168.1.60::docker-cache/pkgcache/
