# syntax=docker/dockerfile:1

# SPDX-FileCopyrightText: Copyright (c) Marcus Holland-Moritz
# SPDX-License-Identifier: MIT

FROM fedora:rawhide@sha256:0c1f63ed8fb818fad16cf6ae091598c410a21d2e1a9adf183beb93189299bfba
RUN dnf update -y
RUN dnf install -y \
        bash-completion \
        vim \
        less
RUN dnf install -y \
        gcc \
        g++ \
        clang \
        man \
        mandoc \
        pip \
        git \
        zstd \
        ccache \
        ninja-build \
        cmake \
        make \
        bubblewrap \
        python-markdown-it-py \
        fuse \
        fuse3 \
        fuse-devel \
        fuse3-devel \
        pkg-config \
        binutils-devel \
        libarchive-devel \
        google-benchmark \
        boost-devel \
        brotli-devel \
        openssl-devel \
        fmt-devel \
        jemalloc-devel \
        lz4-devel \
        xz-devel \
        libzstd-devel \
        xxhash-devel \
        libunwind-devel \
        libdwarf-devel \
        flac-devel \
        utf8cpp-devel \
        json-devel \
        range-v3-devel
RUN useradd -g users -u 1000 -m mhx
USER mhx
ENTRYPOINT /workspace/.docker/build-linux.sh
