# syntax=docker/dockerfile:1

# SPDX-FileCopyrightText: Copyright (c) Marcus Holland-Moritz
# SPDX-License-Identifier: MIT

FROM ubuntu:26.04@sha256:2260313b31c8c011cd2eebe728008efac1b3982be73eb71348ea2648d2c0e09b
RUN apt update && apt upgrade -y
RUN apt install -y \
        bash-completion \
        curl \
        vim \
        less \
        gcc-15 \
        g++-15 \
        gcc-16 \
        g++-16 \
        clang-21 \
        clang-22 \
        git \
        zstd \
        ccache \
        ninja-build \
        cmake \
        make \
        mandoc \
        bubblewrap \
        python3-markdown-it \
        fuse3 \
        pkg-config \
        binutils-dev \
        libacl1-dev \
        libarchive-dev \
        libbenchmark-dev \
        libboost-chrono-dev \
        libboost-context-dev \
        libboost-filesystem-dev \
        libboost-process-dev \
        libboost-program-options-dev \
        libboost-regex-dev \
        libboost-thread-dev \
        libbrotli-dev \
        libjemalloc-dev \
        libiberty-dev \
        liblz4-dev \
        liblzma-dev \
        libzstd-dev \
        libxxhash-dev \
        libmagic-dev \
        libparallel-hashmap-dev \
        librange-v3-dev \
        libssl-dev \
        libunwind-dev \
        libdwarf-dev \
        libelf-dev \
        libfmt-dev \
        libfuse-dev \
        libfuse3-dev \
        libutfcpp-dev \
        libflac++-dev \
        nlohmann-json3-dev
# RUN useradd -g users -u 1000 -m mhx
USER ubuntu
ENTRYPOINT /workspace/.docker/build-linux.sh
