# syntax=docker/dockerfile:1

# SPDX-FileCopyrightText: Copyright (c) Marcus Holland-Moritz
# SPDX-License-Identifier: MIT

FROM debian:latest@sha256:f324c7ff54321e8d9c588493a20244965938ce0aa50bbd1022d38010e9ffc4b1
RUN apt update && apt upgrade -y
RUN apt install -y \
        bash-completion \
        wget \
        curl \
        vim \
        less \
        gcc \
        g++ \
        gcc-12 \
        g++-12 \
        gcc-13 \
        g++-13 \
        gcc-14 \
        g++-14 \
        clang \
        clang-17 \
        clang-18 \
        clang-19 \
        git \
        zstd \
        ccache \
        ninja-build \
        cmake \
        make \
        mandoc \
        bubblewrap \
        python3-markdown-it \
        fuse3 \
        pkg-config \
        binutils-dev \
        libacl1-dev \
        libarchive-dev \
        libbenchmark-dev \
        libboost-chrono-dev \
        libboost-context-dev \
        libboost-filesystem-dev \
        libboost-program-options-dev \
        libboost-regex-dev \
        libboost-thread-dev \
        libbrotli-dev \
        libjemalloc-dev \
        libiberty-dev \
        liblz4-dev \
        liblzma-dev \
        libzstd-dev \
        libxxhash-dev \
        libmagic-dev \
        libparallel-hashmap-dev \
        librange-v3-dev \
        libssl-dev \
        libunwind-dev \
        libdwarf-dev \
        libelf-dev \
        libfmt-dev \
        libfuse-dev \
        libfuse3-dev \
        libutfcpp-dev \
        libflac++-dev \
        nlohmann-json3-dev \
        xz-utils
RUN useradd -g users -u 1000 -m mhx
USER mhx
ENTRYPOINT /workspace/.docker/build-linux.sh
