# syntax=docker/dockerfile:1

# SPDX-FileCopyrightText: Copyright (c) Marcus Holland-Moritz
# SPDX-License-Identifier: MIT

FROM ubuntu:24.04@sha256:33ceb71981b602c1a7443a53469e4dba065f7503eab3078a2d7a57a2ab987517
RUN apt update && apt upgrade -y
RUN apt install -y \
        bash-completion \
        curl \
        vim \
        less \
        gcc-11 \
        g++-11 \
        gcc-12 \
        g++-12 \
        gcc-13 \
        g++-13 \
        gcc-14 \
        g++-14 \
        clang-15 \
        clang-16 \
        clang-17 \
        clang-18 \
        clang-19 \
        git \
        zstd \
        ccache \
        ninja-build \
        cmake \
        make \
        mandoc \
        bubblewrap \
        python3-markdown-it \
        fuse3 \
        pkg-config \
        binutils-dev \
        libacl1-dev \
        libarchive-dev \
        libbenchmark-dev \
        libboost-chrono-dev \
        libboost-context-dev \
        libboost-filesystem-dev \
        libboost-program-options-dev \
        libboost-regex-dev \
        libboost-thread-dev \
        libbrotli-dev \
        libhowardhinnant-date-dev \
        libjemalloc-dev \
        libiberty-dev \
        liblz4-dev \
        liblzma-dev \
        libzstd-dev \
        libxxhash-dev \
        libmagic-dev \
        libparallel-hashmap-dev \
        librange-v3-dev \
        libssl-dev \
        libunwind-dev \
        libdwarf-dev \
        libelf-dev \
        libfmt-dev \
        libfuse-dev \
        libfuse3-dev \
        libutfcpp-dev \
        libflac++-dev \
        nlohmann-json3-dev
# RUN useradd -g users -u 1000 -m mhx
USER ubuntu
ENTRYPOINT /workspace/.docker/build-linux.sh
