#
# Copyright (c) Marcus Holland-Moritz
#
# This file is part of dwarfs.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT
#

from __future__ import annotations

import argparse
import hashlib
import sys


def read_stdin_binary() -> bytes:
    if sys.platform == "win32":
        import msvcrt
        import os

        msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)

    return sys.stdin.buffer.read()


def emit(data: bytes, args: argparse.Namespace) -> str:
    digest = hashlib.sha256(data).hexdigest()
    out: list[str] = []
    w = out.append

    w("/* Generated by embed_blob.py. Do not edit. */")
    w(f"/* {len(data)} bytes, sha256 {digest} */")
    w("")
    w("#include <cstddef>")
    w("#include <span>")
    w("")
    if args.include:
        w(f"#include <{args.include}>")
        w("")

    if args.namespace:
        w(f"namespace {args.namespace} {{")
        w("")

    w("namespace {")
    w("")
    w(f"unsigned char const {args.array}[] = {{")

    per_line = args.bytes_per_line
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        w("  " + "".join(f"0x{b:02x}," for b in chunk))

    w("};")
    w("")
    w("} // namespace")
    w("")
    w(f"std::span<std::byte const> {args.function}() {{")
    w(
        f"  return {{reinterpret_cast<std::byte const*>({args.array}), sizeof({args.array})}};"
    )
    w("}")

    if args.namespace:
        w("")
        w(f"}} // namespace {args.namespace}")

    w("")
    return "\n".join(out)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("-o", "--output", help="output file (default: stdout)")
    p.add_argument("-n", "--namespace", default="", help="enclosing namespace")
    p.add_argument(
        "-f",
        "--function",
        default="embedded_blob",
        help="name of the generated accessor function",
    )
    p.add_argument(
        "-a", "--array", default="k_blob_data", help="name of the internal array"
    )
    p.add_argument(
        "-i", "--include", default="", help="header to include, declaring the function"
    )
    p.add_argument(
        "--bytes-per-line", type=int, default=16, help="bytes per output line"
    )
    p.add_argument(
        "--allow-empty", action="store_true", help="do not fail on empty input"
    )
    args = p.parse_args()

    data = read_stdin_binary()

    if not data and not args.allow_empty:
        print("embed_blob.py: refusing to embed empty input", file=sys.stderr)
        return 1

    text = emit(data, args)

    if args.output:
        # newline="\n" keeps output byte-identical across platforms
        with open(args.output, "w", encoding="ascii", newline="\n") as f:
            f.write(text)
    else:
        sys.stdout.reconfigure(newline="\n")
        sys.stdout.write(text)

    return 0


if __name__ == "__main__":
    sys.exit(main())
